# $     $     $ #
# CloudPayments #
# $     $     $ #
#
# Помощник в монетизации Вашего проекта
# Вопросы по плагину/ошибки/опечатки? - @CloudDonate_support (Telegram)
# Приятного использования!
#
# $     $     $ #

#
# Сообщения плагина
#
messages:
  noPermission: "&9Cloud&bPayments &8- &cУ Вас недостаточно прав!"
  reload: "&9Cloud&bPayments &8- &aПлагин перезагружен! &7({took}мс)"
  debug-enabled: "&9Cloud&bPayments &8- &7Режим откладки &aвключен&7!"
  debug-disabled: "&9Cloud&bPayments &8- &7Режим откладки &cвыключен&7!"

#
# Настройки
#
settings:
  # Режим откладки
  debug-mode: false
  # Раз во сколько будет отправляться запрос
  # ОБЯЗАТЕЛЬНО: 20 - минимальное число
  request-delay: 20
  # Настройки магазина
  shop:
    shop-id: "YOUR-SHOP-ID-HERE"
    shop-key: "YOUR-SHOP-KEY-HERE"
    server-id: "YOUR-SERVER-ID-HERE"

#
# Локальное хранение
#
local-storage:
  # Хранение покупок
  payments:
    enabled: true
    # Формат сообщения который будет добавлятся в txt файл
    format: "<date>: <nickname> - <product_name> [кол-во: <count>] (+<price> рублей). ID платежа: <payment_id>"

#
# Оповещения об покупках
#
messengers:
  telegram:
    enabled: false
    # Токен вашего бота
    api-token: "YOUR-TOKEN-HERE"
    # Телеграм айди администраторов, кому будут приходить сообщения об покупках
    ids:
      - 1
      - 2

#
# Оповещения об покупках в игре
#
in-game-announcements:
  # Название товара (точь-в-точь с сайта)
  Алмазик:
    # Какие действия будут производится при покупке данного товара
    #
    # Доступные действия:
    #  {CHAT_MESSAGE} - Сообщение в чат
    #  {TITLE_MESSAGE}Верхнее сообщение::нижнее сообщение - Сообщение в тайтл игрокам
    #  {ACTIONBAR_MESSAGE} - Сообщение в акшион бар игрокам
    #  {COMMAND} - Дополнительные команды
    #  {SOUND} - Воспроизводит звук
    #
    # Доступные заполнители:
    #  <nickname> - Ник покупателя
    #  <price> - Сумма, которая пришла магазину (с учётом комиссии сервиса)
    #  <product> - Название товара
    #  <count> - Количество купленного товара
    #
    - "{CHAT_MESSAGE}&9Авто&bДонат &8— &fИгрок &7<nickname> &fприобрёл &b&lАлмаз"
    - "{CHAT_MESSAGE}&9Авто&bДонат &8— &fХочешь так-же? Купи донат на сайте: &bcdonate.ru"
